### ISSUE TITLE
How to collect output?

### ISSUE THREAD

**Issue by lounging-lizard** [QuentinWach/image-ranker#10]
I wish to use this project to subjectively compare a large dataset of images to create a ranking.

As an example, lets say I wish to compare hair color between brown and blonde to provide a metric which indicates how close to blonde or brown the hair color is, this way I can account for mixes of the colors (light brown, dirty blonde etc).

After running the application and ranking a series of matches, how can I then output the score for each image.

Ideally it would be some type of JSON (easy to digest) which (for each image in the set) represented an ID for the input image corresponding to its μ & σ.

Is this a currently supported feature? If not what work around could I use to gather this data?

**Comment by QuentinWach** [comment]
There is currently no JSON export feature.

Instead, Image Ranker provides a **.csv file** containing
**['Image file name', 'ELO', 'Uncertainty', 'Upvotes', 'Downvotes']** just as they are displayed in the GUI below. This file should be saved automatically while you are ranking but you can also export it manually.

Is a JSON essential for you and do you believe it would be more valuable for users rather than a simple .csv?

**Comment by lounging-lizard** [comment]
I believe that as a programmer JSON is a better format than CSV for transporting data, however given this project is more likely to be interacted with by data scientists I think CSV might be more appropriate for them and their use case besides I can parse a CSV easily enough.

It would be ideal if I could select the output but not strictly necessary possible a long term feature :)
